# Site settings
title: Yenny Blog
url: "https://pyeeun.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "" # the prefix of your site uri, eg. `"/jekyll-theme-EasyBook"` or empty string `""`
#timezone: Asia/Chongqing
description: >
  One or more sentences introducing this blog.

# Your information
email: charm5231@naver.com
author: 예니(Yenny)
avatar: "https://avatars1.githubusercontent.com/u/33935840?s=460&v=4"
profile: 스물 일곱 뚜벅이 개발자의 메모장
#twitter_username: twitter_username
#github_username:  github_username
profile_links:
  GitHub: "https://github.com/pyeeun"
  Instagram: "https://www.instagram.com/94.yeeun"
  Facebook: "https://www.facebook.com/charm5231"
  # You can add more profile links above, or edit _includes/sidebar.html 

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

excerpt_separator: <!--more-->

header:
  links:             # Links on the header. Link to in-site page with a slash as prefix
    Home: /
    About: /about/
    Category: /category/

permalink: /archivers/:title
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

# https://jekyllrb.com/docs/configuration/#precedence
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
